apiVersion: apps/v1
kind: SET KIND
metadata:
  name: myapp-deployment
  labels:
    app: myapp
    type: front-end
spec:
  template:
    metadata:
      name: myapp-pod
      labels:
        app: myapp
        type: front-end
    spec:
      containers:
        - name: nginx-container
          image: SET NGINX V 1.14.0
  replicas: SET REPLICAS
  selector:
    matchLabels:
      app: myapp
      type: front-end
